---
subtitle: "Validation & contrôle qualité des expert - V3"
cache: true
---


# Introduction

```{r}
#| label: setup

rm(list = ls())

library("tidyverse")
library("readODS")
library("labelled")
library("forestmodel")
library("gtsummary")
library("kableExtra")
library("janitor")
library("irr")
library("ggsci")
library("baseph")
library("colorspace")

exp <- FALSE
theme_gtsummary_language(language = "fr", decimal.mark = ",")
options(OutDec = ",")
```

```{r}
#| label: macro_ic

nbicph <- function(nn, bb, hh, dec = 3) {
  nn <- signif(nn, dec)
  bb <- signif(bb, dec)
  hh <- signif(hh, dec)
  ll <- paste0(nn, " [", bb, " ; ", hh, "]")
  return(ll)
}
```


Pour l'utilisation des graphiques & tableaux ces derniers sont anonymisés. 

Pour usage interne :

- expert 1 :AL TABAA Omar
- expert 2 : OTTAVIANI Sébastien
- expert 3 : ESPITIA Olivier


# Contrôle global

```{r}
#| label: macro-import
#
#
ttn <- read_ods("datas/intra.ods", sheet = "nerf", col_names = TRUE, na = "NA"
) |> 
  clean_names() |> 
  dplyr::select(!coupe) |> 
  mutate(dif = abs(mesure_2 - mesure_1)) |>
  as_tibble()
#
ttg <- read_ods("datas/intra.ods", sheet = "gaine", col_names = TRUE, na = "NA"
) |> 
  clean_names() |> 
  dplyr::select(!coupe) |> 
  mutate(dif = abs(mesure_2 - mesure_1)) |>
  as_tibble()

```



## Analyse par expert



```{r}
#| label: tbl-explicn
#| tbl-cap: Différence des mesures du nerf par les experts

tstu <- NULL

for (i in 1:3){
  no <- paste0("Expert ", i)
  zz <- ttn |> 
    dplyr::filter (nom == no )
  tzz <- t.test(zz$mesure_1, zz$mesure_2, paired = TRUE)
  my <- round(mean(zz$dif, na.rm = TRUE),2)
  et <- round(sd(zz$dif, na.rm = TRUE),2)
  myet <- paste0(my, " ± ",et)
  ll <- c(no, myet, beaup(tzz$p.value))
  tstu <- rbind(tstu,ll)
}

tstu |> 
  as_tibble() |>
  set_names(c("Expert", "Moyenne [IC 95 %]",  "pval")) |> 
    kbl(booktabs = TRUE, longtable = TRUE)|> 
  kable_styling(latex_options = c("striped", "hold_position")) |> 
  add_footnote(c("Moyenne ± écart-type des différences entre les deux mesures répétées par chaque expert.\n P-value calculée sur un test t de Student pour séries appariées"))

    if (exp) {
      tstu |>
        write_ods(path = classeur, sheet = "difnerf", append = TRUE)
    }

```



```{r}
#| label: fig-difnerf
#| fig-cap: Différence des mesures du nerf par les experts

ttn |> 
ggplot() +
  aes(y = dif, x = nom, fill = nom) +
  geom_violin() +
  geom_boxplot(width = 0.2, fill = "grey90") +
    labs(
    title = "Mesures du nerf optique par les experts",
    y = "Diffréence des mesures (mm)"
  ) +
  theme_light() +
  scale_fill_jama() +
  theme(
      plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_blank(),
    axis.title.y = element_text(,
      size = 12,
      angle = 90,
      vjust = .5
    ),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    legend.position = "none"
  )

```

\newpage

```{r}
#| label: tbl-explicf
#| tbl-cap: Mesures de la gaine du nerf par les experts

tstu <- NULL

for (i in 1:3){
  no <- paste0("Expert ", i)
  zz <- ttg |> 
    dplyr::filter (nom == no )
  tzz <- t.test(zz$mesure_1, zz$mesure_2, paired = TRUE)
  my <- round(mean(zz$dif, na.rm = TRUE),2)
  et <- round(sd(zz$dif, na.rm = TRUE),2)
  myet <- paste0(my, " ± ",et)
  ll <- c(no, myet, beaup(tzz$p.value))
  tstu <- rbind(tstu,ll)
}

tstu |> 
  as_tibble() |>
  set_names(c("Expert", "Moyenne [IC 95 %]",  "pval")) |> 
    kbl(booktabs = TRUE, longtable = TRUE)|> 
  kable_styling(latex_options = c("striped", "hold_position")) |> 
  add_footnote(c("Moyenne ± écart-type des différences entre les deux mesures répétées par chaque expert.\n P-value calculée sur un test t de Student pour séries appariées"))

    if (exp) {
      tstu|>
        write_ods(path = classeur, sheet = "difgaine", append = TRUE)
    }

```


```{r}
#| label: fig-difgaine
#| fig-cap: Mesures de la gaine du nerf par les experts

ttg |> 
ggplot() +
  aes(y = dif, x = nom, fill = nom) +
  geom_violin() +
  geom_boxplot(width = 0.2, fill = "grey90") +
    labs(
    title = "Mesures du nerf optique par les experts",
    y = "Diffréence des mesures (mm)"
  ) +
  theme_light() +
  scale_fill_jama() +
  theme(
      plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_blank(),
    axis.title.y = element_text(,
      size = 12,
      angle = 90,
      vjust = .5
    ),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    legend.position = "none"
  )

```
